version: "3.8"

services:
  api_rac_db:
    build: .
    container_name: api_rac_db
    ports:
      - "3001:3001"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx_db_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_rac_db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
