version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=rodrigoAra
      - POSTGRES_PASSWORD=ra123
      - POSTGRES_DB=databases
    ports:
      - "5435:5432"
    networks:
      - app_net
    volumes:
      - pgdata:/bitnami/postgresql

  api_rac_db:
    build: .
    container_name: api_rac_db
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://rodrigoAra:ra123@postgres:5432/databases
    depends_on:
      - postgres
    restart: always
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx_db_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_rac_db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  pgdata:
